version: '3'

services:
  web:
    build: .
    ports:
    - "8000:8000"
	  env_file:
	  - local.env



# nginx?
#  nginx:
#    image: nginx:latest
#    networks:
#      - backend
#    depends_on:
#      - web