{{/* @formatter:off */}}
{{- if .Values.ingress.enabled -}}
{{- $fullname := include "project.fullname" . -}}
{{- $host := include "project.tls.host" . -}}
{{- $baseDomain := include "project.baseDomain" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
{{ include "project.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- if .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget | quote }}
{{- end }}
{{- if .Values.ingress.cors }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
{{- end }}
{{- if .Values.ingress.appRoot }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingress.appRoot | quote }}
{{- end }}
{{- if .Values.ingress.authEnabled }}
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.{{ $baseDomain }}/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/auth-url: "https://login.{{ $baseDomain }}/oauth2/auth"    
{{- end }}
{{- if .Values.ingress.annotations -}}{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}{{- end }}
spec:
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullname }}
              servicePort: http
            path: {{ .Values.ingress.path }}
  tls:
    - hosts:
      - {{ $host | quote }}
      secretName: "{{ $host | replace "." "-" }}-ingress-cert"
{{- end -}}
