# Generated by Django 2.0 on 2020-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(db_index=True, max_length=255, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP Address')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('trusted', models.BooleanField(db_index=True, default=False, verbose_name='Trusted')),
                ('http_accept', models.CharField(max_length=1025, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('get_data', models.TextField(verbose_name='GET Data')),
                ('post_data', models.TextField(verbose_name='POST Data')),
                ('failures_since_start', models.PositiveIntegerField(verbose_name='Failed Logins')),
            ],
            options={
                'verbose_name': 'Access Attempts',
                'verbose_name_plural': 'Access Attempts',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(db_index=True, max_length=255, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP Address')),
                ('username', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Username')),
                ('trusted', models.BooleanField(db_index=True, default=False, verbose_name='Trusted')),
                ('http_accept', models.CharField(max_length=1025, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, verbose_name='Path')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout time')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
            },
        ),
    ]
